#!/bin/bash

#functions 
function hideExtra(){
    read -p "Extensions of files to hide speated by space[html txt ...]: " more
    if [[ ! -d .extra ]]; then 
      mkdir .extra
    fi

    for i in $more; do
      mv *."$i" .extra/
    done
}


# move subtitles to .subs 
read -p "what is the subtitle extension? [srt, vtt, ...]: "  ext

if [[ ! -d .subs ]]; then
  mkdir ./.subs 
fi

mv *.$ext .subs/

# hide extra files 
read -ep "Do you want to hide any extra files [y|n]: " ans

case $ans in 
  y|Y) 
    hideExtra
    ;;
  n|N)
    echo "Ok!, whatever !"
    ;;
  *)
    echo "Enter A Valid Answer Please !"
esac




    
